CREATE TABLE
    IF NOT EXISTS USERS_SHOPPER (
        id VARCHAR(64) PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        cpf VARCHAR(60) UNIQUE NOT NULL
    );

DESCRIBE USERS_SHOPPER;

SELECT * from USERS_SHOPPER;

DROP TABLE USERS_SHOPPER;

CREATE TABLE
    IF NOT EXISTS PRODUCTS_SHOPPER (
        id VARCHAR(64) PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        price VARCHAR(60) NULL,
        qty_stock VARCHAR(60) NULL
    );

DESCRIBE PRODUCTS_SHOPPER;

SELECT * from PRODUCTS_SHOPPER;

DROP TABLE PRODUCTS_SHOPPER;

CREATE TABLE
    IF NOT EXISTS ORDERS_SHOPPER (
        id VARCHAR(64) PRIMARY KEY,
        client_id VARCHAR(255) NULL,
        order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        delivery_date DATE NOT NULL,
        total_order VARCHAR(255) NOT NULL,
        FOREIGN KEY (client_id) REFERENCES USERS_SHOPPER(id) ON DELETE
        SET NULL
    );

DESCRIBE ORDERS_SHOPPER;

SELECT * from ORDERS_SHOPPER;

DROP TABLE ORDERS_SHOPPER;

CREATE TABLE
    ORDERS_PRODUCTS(
        id VARCHAR(64) PRIMARY KEY,
        id_order VARCHAR(255)  NULL,
        id_product VARCHAR(255) NULL,
        quantity VARCHAR(255) NOT NULL,
        FOREIGN KEY (id_order) REFERENCES ORDERS_SHOPPER(id) ON DELETE SET NULL,
        FOREIGN KEY (id_product) REFERENCES PRODUCTS_SHOPPER(id) ON DELETE
        SET NULL
    );

DESCRIBE ORDERS_PRODUCTS;

SELECT * from ORDERS_PRODUCTS;

DROP TABLE ORDERS_PRODUCTS;